# Use an official Node.js runtime as a parent image
FROM node:lts-slim AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and pnpm-lock.yaml to the working directory
COPY package.json pnpm-lock.yaml ./

# Install pnpm
RUN npm install -g pnpm

# Install project dependencies using pnpm
RUN pnpm install

# Copy the rest of the application code to the working directory
COPY . .

# Run the build command to get minimized html/css/js
RUN pnpm build

# Use an official NGINX runtime as a parent image
FROM nginx:alpine-slim

# Copy NGINX configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the build output to NGINX's html directory
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Define the command to run the application
CMD ["nginx", "-g", "daemon off;"]